<?php

declare(strict_types=1);

namespace ComposerMergeDriver\Tests\Merger;

use ComposerMergeDriver\FileType;
use ComposerMergeDriver\MergeContext;
use ComposerMergeDriver\Merger\ComposerLockMerger;
use ComposerMergeDriver\Support\ComposerLibrary;
use ComposerMergeDriver\Tests\Support\MergeFixture;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class ComposerLockMergerTest extends TestCase
{
    private MergeFixture $fixture;
    private ComposerLockMerger $merger;

    protected function setUp(): void
    {
        $this->fixture = new MergeFixture();
        // noResolve is set in MergeFixture::make(); library never called in these tests.
        $this->merger  = new ComposerLockMerger(new ComposerLibrary());
    }

    protected function tearDown(): void
    {
        $this->fixture->cleanup();
    }

    // ─── helpers ─────────────────────────────────────────────────────────────

    /**
     * @param list<array<string, mixed>> $packages
     * @param list<array<string, mixed>> $packagesDev
     * @return array<string, mixed>
     */
    private function lockData(
        array $packages = [],
        array $packagesDev = [],
        string $contentHash = 'abc123',
    ): array {
        return [
            '_readme'        => ['Generated by Composer'],
            'content-hash'   => $contentHash,
            'packages'       => $packages,
            'packages-dev'   => $packagesDev,
            'aliases'        => [],
            'minimum-stability' => 'stable',
            'stability-flags'   => [],
            'prefer-stable'     => false,
            'prefer-lowest'     => false,
            'platform'       => [],
            'platform-dev'   => [],
            'plugin-api-version' => '2.3.0',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function pkg(string $name, string $version, string $ref = ''): array
    {
        return [
            'name'    => $name,
            'version' => $version,
            'dist'    => ['type' => 'zip', 'url' => '', 'reference' => $ref !== '' ? $ref : $version],
        ];
    }

    private function makeLockContext(
        MergeFixture $fixture,
        MergeContext $ctx,
    ): MergeContext {
        // Build a context for composer.lock (re-use the same temp paths)
        return new MergeContext(
            basePath: $ctx->basePath,
            oursPath: $ctx->oursPath,
            theirsPath: $ctx->theirsPath,
            markerSize: 7,
            pathname: 'composer.lock',
            fileType: FileType::ComposerLock,
            workingDir: $ctx->workingDir,
            noResolve: true,
        );
    }

    // ─── tests ───────────────────────────────────────────────────────────────

    #[Test]
    public function unchangedPackagesArePreserved(): void
    {
        $pkgA = $this->pkg('vendor/a', '1.0.0');
        $lock  = $this->lockData([$pkgA]);

        $ctx   = $this->fixture->make($lock, $lock, $lock, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertCount(1, $result['packages']);
        self::assertSame('1.0.0', $result['packages'][0]['version']);
    }

    #[Test]
    public function oursAddedPackageIsKept(): void
    {
        $base  = $this->lockData();
        $ours  = $this->lockData([$this->pkg('vendor/new', '1.0.0')]);
        $theirs = $this->lockData();

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertCount(1, $result['packages']);
        self::assertSame('vendor/new', $result['packages'][0]['name']);
    }

    #[Test]
    public function theirsAddedPackageIsKept(): void
    {
        $base   = $this->lockData();
        $ours   = $this->lockData();
        $theirs = $this->lockData([$this->pkg('vendor/new', '2.0.0')]);

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertCount(1, $result['packages']);
        self::assertSame('vendor/new', $result['packages'][0]['name']);
    }

    #[Test]
    public function bothSidesAddedSamePackageSameVersion(): void
    {
        $base   = $this->lockData();
        $ours   = $this->lockData([$this->pkg('vendor/a', '1.0.0')]);
        $theirs = $this->lockData([$this->pkg('vendor/a', '1.0.0')]);

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertCount(1, $result['packages']);
        self::assertSame('1.0.0', $result['packages'][0]['version']);
    }

    #[Test]
    public function bothSidesAddedSamePackageDifferentVersionsIsConflict(): void
    {
        $base   = $this->lockData();
        $ours   = $this->lockData([$this->pkg('vendor/a', '1.0.0')]);
        $theirs = $this->lockData([$this->pkg('vendor/a', '2.0.0')]);

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        // noResolve = true so composer update won't run; expect conflict.
        self::assertFalse($clean);
        $result = $this->fixture->result($ctx);
        // Best effort: ours wins
        self::assertSame('1.0.0', $result['packages'][0]['version']);
    }

    #[Test]
    public function oursUpdatedPackageTheirsDidNot(): void
    {
        $pkgBase   = $this->pkg('vendor/a', '1.0.0');
        $pkgOurs   = $this->pkg('vendor/a', '1.2.0');
        $pkgTheirs = $this->pkg('vendor/a', '1.0.0');

        $ctx   = $this->fixture->make(
            $this->lockData([$pkgBase]),
            $this->lockData([$pkgOurs]),
            $this->lockData([$pkgTheirs]),
            'composer.lock'
        );
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertSame('1.2.0', $result['packages'][0]['version']);
    }

    #[Test]
    public function theirsUpdatedPackageOursDidNot(): void
    {
        $pkgBase   = $this->pkg('vendor/a', '1.0.0');
        $pkgOurs   = $this->pkg('vendor/a', '1.0.0');
        $pkgTheirs = $this->pkg('vendor/a', '1.3.0');

        $ctx   = $this->fixture->make(
            $this->lockData([$pkgBase]),
            $this->lockData([$pkgOurs]),
            $this->lockData([$pkgTheirs]),
            'composer.lock'
        );
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertSame('1.3.0', $result['packages'][0]['version']);
    }

    #[Test]
    public function oursRemovedPackageThatTheirsDidNotTouch(): void
    {
        $pkgA  = $this->pkg('vendor/a', '1.0.0');
        $base  = $this->lockData([$pkgA]);
        $ours  = $this->lockData();
        $theirs = $this->lockData([$pkgA]);

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertCount(0, $result['packages']);
    }

    #[Test]
    public function theirsRemovedPackageThatOursDidNotTouch(): void
    {
        $pkgA  = $this->pkg('vendor/a', '1.0.0');
        $base  = $this->lockData([$pkgA]);
        $ours  = $this->lockData([$pkgA]);
        $theirs = $this->lockData();

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $clean = $this->merger->merge($ctx);

        self::assertTrue($clean);
        $result = $this->fixture->result($ctx);
        self::assertCount(0, $result['packages']);
    }

    #[Test]
    public function metadataMinimumStabilityTakenFromTheirsIfOnlyTheyChanged(): void
    {
        $base   = $this->lockData();
        $ours   = $this->lockData();
        $theirs = $this->lockData();
        $theirs['minimum-stability'] = 'dev';

        $ctx   = $this->fixture->make($base, $ours, $theirs, 'composer.lock');
        $this->merger->merge($ctx);
        $result = $this->fixture->result($ctx);

        self::assertSame('dev', $result['minimum-stability']);
    }

    #[Test]
    public function contentHashIsUpdatedFromExistingComposerJson(): void
    {
        $composerJson = ['name' => 'test/pkg', 'require' => ['php' => '^8.1']];
        $tmpDir       = sys_get_temp_dir() . '/cmd-hash-test-' . bin2hex(random_bytes(4));
        mkdir($tmpDir, 0700, true);
        file_put_contents(
            $tmpDir . '/composer.json',
            json_encode($composerJson, JSON_THROW_ON_ERROR)
        );

        $lock = $this->lockData(contentHash: 'old-hash');
        $ctx  = $this->fixture->make($lock, $lock, $lock, 'composer.lock', $tmpDir);
        $this->merger->merge($ctx);
        $result = $this->fixture->result($ctx);

        self::assertNotSame('old-hash', $result['content-hash']);

        // clean up
        unlink($tmpDir . '/composer.json');
        rmdir($tmpDir);
    }
}
